<?xml version="1.0" encoding="utf-8"?><Database Name="JobStatistics" Class="DatabaseObjectsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\JobStatistics.mdf;Integrated Security=True" SettingsObjectName="CosmosJobMonitor.Share.Properties.Settings" SettingsPropertyName="JobStatisticsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserAliasesForTracking" Member="UserAliasesForTrackings">
    <Type Name="UserAliasesForTracking">
      <Column Name="Alias" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JobStatistics" Member="JobStatistics">
    <Type Name="JobStatistic">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HyperLink" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrueUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubmitTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalRunningTimeInSecond" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PNSeconds" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>