#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosJobMonitor.Share
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JobStatistics")]
	public partial class DatabaseObjectsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserAliasesForTracking(UserAliasesForTracking instance);
    partial void UpdateUserAliasesForTracking(UserAliasesForTracking instance);
    partial void DeleteUserAliasesForTracking(UserAliasesForTracking instance);
    partial void InsertJobStatistic(JobStatistic instance);
    partial void UpdateJobStatistic(JobStatistic instance);
    partial void DeleteJobStatistic(JobStatistic instance);
    #endregion
		
		public DatabaseObjectsDataContext() : 
				base(global::CosmosJobMonitor.Share.Properties.Settings.Default.JobStatisticsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseObjectsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseObjectsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseObjectsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseObjectsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserAliasesForTracking> UserAliasesForTrackings
		{
			get
			{
				return this.GetTable<UserAliasesForTracking>();
			}
		}
		
		public System.Data.Linq.Table<JobStatistic> JobStatistics
		{
			get
			{
				return this.GetTable<JobStatistic>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAliasesForTracking")]
	public partial class UserAliasesForTracking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Alias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    #endregion
		
		public UserAliasesForTracking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobStatistics")]
	public partial class JobStatistic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _HyperLink;
		
		private string _UserName;
		
		private string _TrueUserName;
		
		private int _State;
		
		private System.Nullable<System.DateTime> _SubmitTime;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _EndTime;
		
		private System.Nullable<long> _TotalRunningTimeInSecond;
		
		private System.Nullable<long> _PNSeconds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHyperLinkChanging(string value);
    partial void OnHyperLinkChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTrueUserNameChanging(string value);
    partial void OnTrueUserNameChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnSubmitTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmitTimeChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    partial void OnTotalRunningTimeInSecondChanging(System.Nullable<long> value);
    partial void OnTotalRunningTimeInSecondChanged();
    partial void OnPNSecondsChanging(System.Nullable<long> value);
    partial void OnPNSecondsChanged();
    #endregion
		
		public JobStatistic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HyperLink", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HyperLink
		{
			get
			{
				return this._HyperLink;
			}
			set
			{
				if ((this._HyperLink != value))
				{
					this.OnHyperLinkChanging(value);
					this.SendPropertyChanging();
					this._HyperLink = value;
					this.SendPropertyChanged("HyperLink");
					this.OnHyperLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrueUserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrueUserName
		{
			get
			{
				return this._TrueUserName;
			}
			set
			{
				if ((this._TrueUserName != value))
				{
					this.OnTrueUserNameChanging(value);
					this.SendPropertyChanging();
					this._TrueUserName = value;
					this.SendPropertyChanged("TrueUserName");
					this.OnTrueUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmitTime
		{
			get
			{
				return this._SubmitTime;
			}
			set
			{
				if ((this._SubmitTime != value))
				{
					this.OnSubmitTimeChanging(value);
					this.SendPropertyChanging();
					this._SubmitTime = value;
					this.SendPropertyChanged("SubmitTime");
					this.OnSubmitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalRunningTimeInSecond", DbType="BigInt")]
		public System.Nullable<long> TotalRunningTimeInSecond
		{
			get
			{
				return this._TotalRunningTimeInSecond;
			}
			set
			{
				if ((this._TotalRunningTimeInSecond != value))
				{
					this.OnTotalRunningTimeInSecondChanging(value);
					this.SendPropertyChanging();
					this._TotalRunningTimeInSecond = value;
					this.SendPropertyChanged("TotalRunningTimeInSecond");
					this.OnTotalRunningTimeInSecondChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNSeconds", DbType="BigInt")]
		public System.Nullable<long> PNSeconds
		{
			get
			{
				return this._PNSeconds;
			}
			set
			{
				if ((this._PNSeconds != value))
				{
					this.OnPNSecondsChanging(value);
					this.SendPropertyChanging();
					this._PNSeconds = value;
					this.SendPropertyChanged("PNSeconds");
					this.OnPNSecondsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
